### ISSUE TITLE
Consolidate with JyIDV or IJython repo? None of my business, just in tidying-up mode. 

### ISSUE THREAD

**Issue by brianmapes** [suvarchal/jython_notebooks#1]

**Comment by suvarchal** [comment]
This repo is just pure Java-Jython stuff sperate from IDV, my new place holder for my experiments in jython that i started to loose in my laptop, given how rare i work in jython it these days. 

JyIDV ais the one which should go in drilsdown, IJython is not related to drilsdown, i suppose. IJython, if and when i fix it is for a broader community of jython users, who would like to use jython in jupyter.

**Comment by brianmapes** [comment]
OK we will copy JyIDV into the drilsdown (nothing new there, right? Current is current?)


And leave IJython to be your own thing.


Thanks for clarifying.


Brian and Cece

________________________________
